version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8080:80
    depends_on:
      - nodeapp
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: mysql
    restart: always
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d/
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-network

  nodeapp:
    container_name: nodeapp
    entrypoint: wait-for mysql:3306 -t 40 -- npm start
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

